"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import sys
import dj_database_url
import os              # <--- os di-import DI SINI
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TESTING = 'test' in sys.argv


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j89$67q1y!ef&gwuvolss1h84qfzj^g&r8pfk0)_2%nm6*6mzf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    'https://*.railway.app',
    'http://localhost:3000',
    'http://localhost:8080',
    'https://newt-shoes-project-production.up.railway.app',
    'https://newt-shoes-backend.up.railway.app'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders', # Tambahkan ini
    'rest_framework',
    'drf_yasg',  # <--- Tambahkan ini
    'shoes',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Wajib ditaruh paling atas
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Deteksi apakah aplikasi berjalan di dalam server Railway
IS_RAILWAY = os.environ.get('RAILWAY_ENVIRONMENT_NAME') is not None or os.environ.get('PORT') is not None

if IS_RAILWAY:
    # Mengambil string koneksi penuh yang dijamin disediakan oleh Railway
    db_url = os.environ.get('DATABASE_URL') or os.environ.get('PGURL') or os.environ.get('POSTGRES_URL')
    
    if db_url:
        # dj_database_url akan otomatis mengurai user, password, host, port, dan db name dari satu URL tersebut
        DATABASES = {
            'default': dj_database_url.parse(db_url, conn_max_age=600)
        }
        # Siasati agar engine-nya dipaksa menggunakan postgresql bawaan django
        DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'
    else:
        # Fallback cadangan jika url utama tidak terbaca
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.environ.get('PGDATABASE', 'railway'),
                'USER': os.environ.get('PGUSER', 'postgres'),
                'PASSWORD': os.environ.get('PGPASSWORD'),
                'HOST': 'postgres.railway.internal',
                'PORT': os.environ.get('PGPORT', '5432'),
            }
        }
    
else:
    # Setelan MySQL lokal untuk laptop kamu saat development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DB_NAME', 'newt_shoes'),
            'USER': os.environ.get('DB_USER', 'root'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'root'),
            'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DB_PORT', '3306'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Simple logging to console so container logs show app messages (info+)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Izinkan frontend Next.js (port 3000) untuk mengambil data dari Django
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Supaya laptopmu masih bisa testing
    "https://newt-shoes-project.vercel.app",  # Ganti dengan domain asli dari Vercel frontend-mu nanti
    "http://localhost:3001",
    "http://localhost:3002",
    "http://localhost:3003",
    "http://localhost:3004",
    "http://localhost:3005",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
]

# ==========================================
# KONFIGURASI TAMBAHAN PERTEMUAN 10
# ==========================================
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/minute',
    },
    # Tambahkan baris Pagination bawaan DRF di bawah ini:
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,  # Batasi otomatis default 5 data per halaman
}


# ==========================================================
# PERTEMUAN 11: PENGALIHAN DATABASE & ABAIKAN MIGRATIONS UNTUK TESTING
# ==========================================================
if TESTING:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }
    # Tambahkan baris ini agar Django tidak membaca file migrasi lama yang rusak saat testing
    MIGRATION_MODULES = {
        'shoes': None,
    }