# Generated by Django 5.2.13 on 2026-05-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'managed': True},
        ),
    ]
