# Generated by Django 5.2.13 on 2026-05-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_alter_bookings_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='booking_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='bookings',
            name='pickup_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='shoes_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='shoes_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='user_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
