# Generated by Django 5.2.13 on 2026-05-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_rename_booking_id_bookings_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
