# Generated by Django 5.2.13 on 2026-07-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
